version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_archive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root456
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: weather_archive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root456
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: